/**
 * This function is used to organize data to be sent to the client.
 * @param data - Data retrieved from findAndCountAll, containing data.rows and data.count
 * @param page - The current page, can be a number but can also be null or undefined
 * @param limit - The limit per page, default is 10
 * @returns The response data generated by the API
 *
 * Example:
 * ```javascript
 * const response = indexResponse(data, 1, 10);
 *
 * console.log(response)
 * // Output
 * // {
 * //   status: 'success',
 * //   message: 'Retrieved data successfully',
 * //   currentPage: 1,
 * //   totalPages: 1,
 * //   startItem: 1,
 * //   endItem: 3,
 * //   itemLength: 3,
 * //   totalItems: 3,
 * //   data: [
 * //       {....},
 * //       {....},
 * //       {....}
 * //   ],
 * // }
 *```
 */
export const indexResponse = (
  data: { rows: any; count: number },
  page: any,
  limit: number
) => {
  const dataLength = data?.rows?.length || 0;
  const isDataExists = dataLength > 0;

  const response = {
    status: 'success',
    message: isDataExists
      ? 'Retrieved data successfully'
      : 'No data to display',
    currentPage: page ? +page : 1,
    totalPages: Math.ceil(data.count / limit),
    startItem: isDataExists ? limit * (page ? +page - 1 : 0) + 1 : 0,
    endItem: isDataExists ? limit * (page ? +page - 1 : 0) + dataLength : 0,
    itemLength: dataLength,
    totalItems: data.count || 0,
    data: data.rows || [],
  };

  return response;
};
